graph TD;
    A[Observación] -->|Datos crudos| B[Preprocesamiento]
    B --> C[Limpieza y procesamiento de datos]
    C1[código] -->
    C --> D[Análisis de Datos]
    D1[código] -->
    D --> E[Modelado]
    E1[Código] --> E
    E --> F[Salida]

